//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbookDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsOrder
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> idOrder { get; set; }
        public Nullable<System.Guid> idDiscount { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Order Order { get; set; }
    }
}
