//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbookDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListLike
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> idPoster { get; set; }
        public Nullable<System.Guid> idAccount { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Poster Poster { get; set; }
    }
}
