//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbookDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Carts = new HashSet<Cart>();
            this.DetailsOrders = new HashSet<DetailsOrder>();
        }
    
        public System.Guid idOrder { get; set; }
        public string address { get; set; }
        public string fullname { get; set; }
        public string methodPay { get; set; }
        public string numberPhone { get; set; }
        public Nullable<long> total { get; set; }
        public string totalMoneyProduct { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> ship { get; set; }
        public Nullable<System.Guid> idBill { get; set; }
        public Nullable<System.Guid> idDiscount { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsOrder> DetailsOrders { get; set; }
    }
}
