//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbookDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poster()
        {
            this.Category_Poster = new HashSet<Category_Poster>();
            this.ListLikes = new HashSet<ListLike>();
        }
    
        public System.Guid idPoster { get; set; }
        public string title { get; set; }
        public string sub { get; set; }
        public string disciption { get; set; }
        public string urlImage { get; set; }
        public System.Guid listLike { get; set; }
        public System.Guid idCategory { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Poster> Category_Poster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListLike> ListLikes { get; set; }
    }
}
