//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbookDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Category_Product = new HashSet<Category_Product>();
            this.DetailCarts = new HashSet<DetailCart>();
        }
    
        public System.Guid idProduct { get; set; }
        public string name { get; set; }
        public string imageBef { get; set; }
        public string imageAf { get; set; }
        public string quantity { get; set; }
        public string thumbnails { get; set; }
        public string description { get; set; }
        public string rating { get; set; }
        public bool hot { get; set; }
        public bool sale { get; set; }
        public long priceOld { get; set; }
        public long priceSale { get; set; }
        public System.Guid idAuthor { get; set; }
        public System.Guid idCategory { get; set; }
        public System.Guid idCart { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Product> Category_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailCart> DetailCarts { get; set; }
    }
}
